# Fluorologger configuration
# Copy template to config.yaml and edit as needed

read_time: 1 # time between fluorometer/GPS readings
#gps_port: COM10 #log GPS elsewhere

# Fluorometer calibration
cal:
  # di water and old turner 400
  # std_concentration: 400.0 # concentration of standard solution in ppb
  # std_voltage: 1.83076
  # std_gain: 1 # gain setting for standard solution
  # blank_1x: -0.00597 # blank reading for 1x gain
  # blank_10x: 0.00056 # blank reading for 10x gain 
  # blank_100x: 0.06630 # blank reading for 100x gain

  # new turner 400 and ESL seawater
  # std_concentration: 400.0 # concentration of standard solution in ppb
  # std_voltage: 2.378 # static
  # std_voltage: 2.38534 # pumped, don't use
  # std_gain: 1 # gain setting for standard solution
  # blank_1x: 0.00201 # blank reading for 1x gain
  # blank_10x: 0.08100 # blank reading for 10x gain 
  # blank_100x: 0.86441 # blank reading for 100x gain

  # Fluorometer calibration settings
  # Use these parameters for the Turner cal method
  std_concentration: 400.0 # concentration of standard solution in ppb
  std_voltage: 2.425516
  std_gain: 1 # gain setting for standard solution
  blank_1x: 0.03183 # blank reading for 1x gain
  blank_10x: 0.1225 # blank reading for 10x gain 
  blank_100x: 1.0218 # blank reading for 100x gain

# Fluorometer gain
gain:
  auto: True
  gain: 1

# Output files
file:
  data: C:/Users/CSL 2/Documents/LOCNESS_data/rhodamine.csv
  log: C:/Users/CSL 2/Documents/LOCNESS_data/rhodamine.log

# Database settings
db:
  filename: C:/Users/CSL 2/Documents/LOCNESS_data/locness.db
  table: rhodamine