# Fluorologger configuration
# Copy template to config.yaml and edit as needed

read_time: 1 # time between fluorometer/GPS readings
gps_port: COM10

# Fluorometer calibration
cal:
  slope_1x: 2.30415E-1
  slope_10x: 2.31214E-2
  slope_100x: 2.3824E-3
  offset_1x: -9.21659E-1
  offset_10x: -2.31214E-1
  offset_100x: -1.4532E-1

# Fluorometer gain
gain:
  auto: True
  gain: 1

# Output files
file:
  log: fluorometer.log
  data: fluorometer.csv
  db: fluorometer.db
  #log: C:/Users/CSL 2/Documents/LOCNESS_data/underway.log
  #data: C:/Users/CSL 2/Documents/LOCNESS_data/fluorometer.csv
  #db: C:/Users/CSL 2/Documents/LOCNESS_data/underway.db